# Initializing Different Types of Arrays

In [2]:
import numpy as np

In [3]:
# All zeros matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
# All zeros matrix, 2D
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# All zeros matrix, 3D
np.zeros((2, 3, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [9]:
# All zeros matrix, 4D
np.zeros((2, 3, 2, 5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [12]:
# All 1s matrix, 3D
np.ones((2, 3, 5), dtype='int32')

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [13]:
# All n(s) matrix, n = any number
np.full((2, 3), 55)

array([[55, 55, 55],
       [55, 55, 55]])

In [21]:
# Any other number (full_like)
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

# Create an array like `a` but with a different number for all the items
print('--- full_like ---')
print(np.full_like(a, 5))

# Same as above
print('--- full ---')
np.full(a.shape, 7)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
--- full_like ---
[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]]
--- full ---


array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [26]:
# Random decimal numbers
np.random.rand(3, 2, 5)

array([[[0.60945174, 0.29784974, 0.94261531, 0.87393708, 0.49862298],
        [0.03778869, 0.93824828, 0.5137144 , 0.2203544 , 0.83623581]],

       [[0.87543043, 0.5094325 , 0.46933765, 0.01818074, 0.43140243],
        [0.9242882 , 0.66550055, 0.91869413, 0.10592572, 0.93153518]],

       [[0.67518553, 0.02786961, 0.00569673, 0.65203569, 0.32643995],
        [0.68012032, 0.77724741, 0.253567  , 0.50164273, 0.61942071]]])

In [27]:
# Random decimal numbers
np.random.random_sample(a.shape)

array([[0.64551217, 0.95434752, 0.80552986, 0.00978483, 0.62960002,
        0.71795998, 0.32183493],
       [0.68653635, 0.32893472, 0.92386665, 0.51298641, 0.56816297,
        0.0309492 , 0.46328539]])

In [31]:
# Random integer numbers
np.random.randint(-100, 100, size=(3, 3))

array([[  9,  38,   7],
       [-25,  64,  67],
       [  8,  64,  60]])

In [35]:
# The Identity Matrix
np.identity(5, dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [44]:
# Repeat an array
arr = np.array([[1, 2, 3]])
print(arr)
copy = np.repeat(arr, 3, axis=0)
copy

[[1 2 3]]


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [56]:
# Create a matrix with a specific (the following) shape/value combo
# [
#     [1, 1, 1, 1, 1],
#     [1, 0, 0, 0, 1],
#     [1, 0, 9, 0, 1],
#     [1, 0, 0, 0, 1],
#     [1, 1, 1, 1, 1]
# ]

output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

print(output[1:4, 1:4])
output[1:4, 1:4] = z
output

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Be Careful while copying arrays

In [59]:
# WRONG
x = np.array([1, 2, 3])
y = x
y[0] = 100
print(x)
print(y)

[100   2   3]
[100   2   3]


In [61]:
# CORRECT
x = np.array([1, 2, 3])
y = x.copy()
y[0] = 100
print(x)
print(y)

[1 2 3]
[100   2   3]
