# Mathematics

NumPy supports a wide range of mathematical operations. There are many functions available for maths.

### Reference(s)
* [https://numpy.org/doc/stable/reference/routines.math.html](https://numpy.org/doc/stable/reference/routines.math.html)

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [4]:
a + 2

array([3, 4, 5, 6])

In [5]:
a - 2

array([-1,  0,  1,  2])

In [6]:
a * 2

array([2, 4, 6, 8])

In [7]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [11]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [12]:
a ** 2

array([ 1,  4,  9, 16])

In [14]:
# Trigonometry as well
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## Linear Algebra

### Reference(s)
* [https://numpy.org/doc/stable/reference/routines.linalg.html](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [16]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

# Matrix multiplication
# https://www.mathsisfun.com/algebra/matrix-multiplying.html
np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [19]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics

### Reference(s)
* [https://numpy.org/doc/stable/reference/routines.statistics.html](https://numpy.org/doc/stable/reference/routines.statistics.html)

In [20]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.min(stats)

1

In [22]:
np.min(stats, axis=1)

array([1, 4])

In [25]:
np.max(stats)

6

In [26]:
np.max(stats, axis=0)

array([4, 5, 6])