# Pop Quiz

In [1]:
import numpy as np

In [4]:
a = np.array(
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]
    ]
)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [13]:
# Question 1
a[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [24]:
# Question 2
b = a[0:4, 1:5]
np.diag(b)

# Same as above
# a[ [0, 1, 2, 3], [1, 2, 3, 4] ]

array([ 2,  8, 14, 20])

In [43]:
# Question 3
a[[0, 4, 5], 3: ]

array([[ 4,  5],
       [24, 25],
       [29, 30]])