# Accessing/Changing specific elements, rows, columns, etc

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [3]:
# Get a specific element [r, c]
print(a[1, 5])
print(a[1, -2])

13
13


In [4]:
# Get a specific row
print(a[0, :])
print(a[0])

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [5]:
# Get a specific column
print(a)
a[:, 1]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([2, 9])

In [6]:
# Get a little more fancy [start:end:step]
a[0, 1:6:2]  # first row, every alternating item between 2nd and 7th element

array([2, 4, 6])

In [7]:
# Change a specific valuethree
a[1, 5] = 555
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12 555  14]]


In [8]:
# Change an entire column
a[:, 2] = 2010
print(a)

a[:, 4] = [512, 1024]
print(a)

[[   1    2 2010    4    5    6    7]
 [   8    9 2010   11   12  555   14]]
[[   1    2 2010    4  512    6    7]
 [   8    9 2010   11 1024  555   14]]
