# Iterating Over Arrays

We can iterate over a NumPy array just like we would a normal Python list or any oter iterable for that matter.

## Iterating over a One-dimensional Array

Just like a list or any other iterable object, iteration over NumPy arrays can look like this,


In [2]:
import numpy as np

In [3]:
arr = np.arange(12)
for i in arr:
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

## Iterating over a Two-dimensional Array

Iterating over a 2D array is similar.

In [23]:
# We can iterate by row
arr = np.random.randint(32, size=(3, 5))
for row in arr:
    print(row)

[13  4  9 19 10]
[17 15 12 16 24]
[ 9 29 30 20 12]


In [24]:
# or, we can get to each item in the array with nested for loops
for row in arr:
    for item in row:
        print(item, end=' ')

13 4 9 19 10 17 15 12 16 24 9 29 30 20 12 

In [25]:
# We can achieve the above result with the `.flatten()` NumPy method
for item in arr.flatten():
    print(item, end=' ')

13 4 9 19 10 17 15 12 16 24 9 29 30 20 12 

# The `nditer` Object

According to the official NumPy docs,

> The iterator object nditer, introduced in NumPy 1.6, provides many flexible ways to visit all the elements of one or more arrays in a systematic fashion.

Let's have a look.

In [26]:
# One-dimensional array
arr = np.arange(12)
for item in np.nditer(arr):
    print(item, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

In [48]:
# 2D array
arr = np.arange(15).reshape(3, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
# Iterating over the 2D array with `nditer` automatically flattens it
for i in np.nditer(arr):
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 

# Iteration order

Additionally, you can speecify the order to iterate over the 2D array. You can specify the order using the `order` keyword argument.

Available orders,

- `C` - C Order, traverses the array elements horizontally
- `F` - Fortran Order, traverses the array elements vertically

In [38]:
# `C` order example
print(arr, '\n')
for i in np.nditer(arr, order='C'):
    print(i, end=' ')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 

In [39]:
# `F` order example
print(arr, '\n')
for i in np.nditer(arr, order='F'):
    print(i, end=' ')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

0 5 10 1 6 11 2 7 12 3 8 13 4 9 14 

An important thing to be aware of for the iteration is that the order is chosen to match the memory layout of the array instead of using a standard C or Fortran ordering. This is done for access efficiency, reflecting the idea that by default one simply wants to visit each element without concern for a particular ordering.

The elements of both `arr` and `arr.T` get traversed in the same order, namely the order they are stored in memory.

In [42]:
print(arr, '\n')
for i in np.nditer(arr):
    print(i, end=' ')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 

In [43]:
print(arr.T, '\n')
for i in np.nditer(arr.T):
    print(i, end=' ')

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] 

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 

# Modifying Array Values

By default, the `nditer` treats the input operand as a read-only object. To be able to modify the array elements, you must specify either read-write or write-only mode using the `readwrite` or `writeonly` per-operand flags.

The `nditer` will then yield writeable buffer arrays which you may modify. However, because the `nditer` must copy this buffer data back to the original array once iteration is finished, you must signal when the iteration is ended, by one of two methods. You may either:

- used the nditer as a context manager using the with statement, and the temporary data will be written back when the context is exited.
- call the iterator’s close method once finished iterating, which will trigger the write-back.

The nditer can no longer be iterated once either close is called or its context is exited.

In [44]:
# Error with read-only mode
for i in np.nditer(arr):
    i[...] = i * 2

ValueError: assignment destination is read-only

In [54]:
# Modifying the array
arr = np.arange(15).reshape(3, 5)
print(arr)

for i in np.nditer(arr, op_flags=['readwrite']):
    i[...] = i * 2

arr

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [3]:
# with context manager
arr = np.arange(15).reshape(3, 5)
print(arr)

with np.nditer(arr, op_flags=['readwrite']) as it:
    for i in it:
        i[...] = 2 * i

arr

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

# References

- [https://www.pluralsight.com/guides/numpy-arrays-iterating](https://www.pluralsight.com/guides/numpy-arrays-iterating)
- [https://numpy.org/doc/stable/reference/arrays.nditer.html](https://numpy.org/doc/stable/reference/arrays.nditer.html)