# Reorganizing Arrays

### Reference(s)
* [https://numpy.org/doc/stable/reference/routines.array-manipulation.html](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)

In [2]:
import numpy as np

In [7]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape(4, 2)
after

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
# Vertically stacking matrices (vectors)
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
np.vstack([x, y, x])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [19]:
# Horizontal stack
i = np.ones((2, 3))
print(i)

j = np.zeros((2, 2))
print(j)

np.hstack([i, j])

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])