# 3D Example

In [2]:
import numpy as np

In [3]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [4]:
# Get specific element (work outside in)
b[0, 1, 1]

4

In [5]:
# Changing values
b[0, 1, 1] = 100
b

array([[[  1,   2],
        [  3, 100]],

       [[  5,   6],
        [  7,   8]]])

In [6]:
# Changing values
b[0, 1, :] = [4, 5]
b

array([[[1, 2],
        [4, 5]],

       [[5, 6],
        [7, 8]]])

In [7]:
# Changing values
b[0, :, :] = [[10, 20], [30, 40]]
b

array([[[10, 20],
        [30, 40]],

       [[ 5,  6],
        [ 7,  8]]])

In [8]:
# Changing values
b[1, :, :] = [ [100, 200], [500, 600] ]
b

array([[[ 10,  20],
        [ 30,  40]],

       [[100, 200],
        [500, 600]]])

In [9]:
# Changing values
b[:, 1, :] = [ [25, 50], [125, 625] ]
b

array([[[ 10,  20],
        [ 25,  50]],

       [[100, 200],
        [125, 625]]])